
obj-m += mounted.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

test:
	sudo insmod mounted.ko
	cat /proc/mymount
	sudo rmmod mounted
